# 코드 7-6 부분
apiVersion: batch/v1
kind: Job
metadata:
  name: grpc-productinfo-client
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: grpc-productinfo-client
        image: kasunindrasiri/grpc-productinfo-client
      restartPolicy: Never
  backoffLimit: 4