// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order_management.proto

package ecommerce

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Items                []string `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Destination          string   `protobuf:"bytes,5,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_6653354279552460, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Order) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Order) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func init() {
	proto.RegisterType((*Order)(nil), "ecommerce.Order")
}

func init() {
	proto.RegisterFile("order_management.proto", fileDescriptor_6653354279552460)
}

var fileDescriptor_6653354279552460 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x5d, 0x4a, 0xc4, 0x30,
	0x10, 0x80, 0x49, 0xd7, 0x0a, 0x8d, 0xa2, 0x12, 0x44, 0xca, 0x22, 0x52, 0x7c, 0xea, 0x53, 0x16,
	0xf4, 0x02, 0x5e, 0x40, 0x84, 0x2e, 0xf8, 0x2a, 0xd9, 0x64, 0x0c, 0x03, 0x9b, 0x1f, 0x26, 0x29,
	0x1e, 0xc1, 0x6b, 0xcb, 0x26, 0xb6, 0xec, 0xe3, 0x7c, 0x33, 0x5f, 0xc8, 0xc7, 0x1f, 0x02, 0x19,
	0xa0, 0x2f, 0xa7, 0xbc, 0xb2, 0xe0, 0xc0, 0x67, 0x19, 0x29, 0xe4, 0x20, 0x3a, 0xd0, 0xc1, 0x39,
	0x20, 0x0d, 0xdb, 0x27, 0x1b, 0x82, 0x3d, 0xc2, 0xae, 0x2c, 0x0e, 0xf3, 0xf7, 0xee, 0x87, 0x54,
	0x8c, 0x40, 0xa9, 0x9e, 0x3e, 0xff, 0x32, 0xde, 0x7e, 0x9c, 0x5e, 0x11, 0x37, 0xbc, 0x41, 0xd3,
	0xb3, 0x81, 0x8d, 0xdd, 0xd4, 0xa0, 0x11, 0xf7, 0xbc, 0xc5, 0x0c, 0x2e, 0xf5, 0xcd, 0xb0, 0x19,
	0xbb, 0xa9, 0x0e, 0x62, 0xe0, 0x57, 0x06, 0x92, 0x26, 0x8c, 0x19, 0x83, 0xef, 0x37, 0xe5, 0xfc,
	0x1c, 0x9d, 0xbc, 0x48, 0xa8, 0xa1, 0xbf, 0x18, 0xd8, 0xd8, 0x4c, 0x75, 0xf8, 0xf7, 0x32, 0x7a,
	0x55, 0xbc, 0x76, 0xf5, 0x16, 0xf4, 0xb2, 0xe7, 0xb7, 0xe5, 0x23, 0xef, 0x6b, 0x8d, 0x78, 0xe3,
	0xd7, 0x73, 0x34, 0x2a, 0x43, 0x59, 0x24, 0x71, 0x27, 0xd7, 0x30, 0x59, 0xd0, 0xf6, 0x51, 0xd6,
	0x3e, 0xb9, 0xf4, 0xc9, 0x7d, 0x26, 0xf4, 0xf6, 0x53, 0x1d, 0x67, 0x18, 0xd9, 0xe1, 0xb2, 0xf0,
	0xd7, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x54, 0x22, 0xd5, 0x6e, 0x2a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrderManagementClient is the client API for OrderManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderManagementClient interface {
	// ...
	UpdateOrders(ctx context.Context, opts ...grpc.CallOption) (OrderManagement_UpdateOrdersClient, error)
}

type orderManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderManagementClient(cc grpc.ClientConnInterface) OrderManagementClient {
	return &orderManagementClient{cc}
}

func (c *orderManagementClient) UpdateOrders(ctx context.Context, opts ...grpc.CallOption) (OrderManagement_UpdateOrdersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_OrderManagement_serviceDesc.Streams[0], "/ecommerce.OrderManagement/updateOrders", opts...)
	if err != nil {
		return nil, err
	}
	x := &orderManagementUpdateOrdersClient{stream}
	return x, nil
}

type OrderManagement_UpdateOrdersClient interface {
	Send(*Order) error
	CloseAndRecv() (*wrappers.StringValue, error)
	grpc.ClientStream
}

type orderManagementUpdateOrdersClient struct {
	grpc.ClientStream
}

func (x *orderManagementUpdateOrdersClient) Send(m *Order) error {
	return x.ClientStream.SendMsg(m)
}

func (x *orderManagementUpdateOrdersClient) CloseAndRecv() (*wrappers.StringValue, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(wrappers.StringValue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OrderManagementServer is the server API for OrderManagement service.
type OrderManagementServer interface {
	// ...
	UpdateOrders(OrderManagement_UpdateOrdersServer) error
}

// UnimplementedOrderManagementServer can be embedded to have forward compatible implementations.
type UnimplementedOrderManagementServer struct {
}

func (*UnimplementedOrderManagementServer) UpdateOrders(srv OrderManagement_UpdateOrdersServer) error {
	return status.Errorf(codes.Unimplemented, "method UpdateOrders not implemented")
}

func RegisterOrderManagementServer(s *grpc.Server, srv OrderManagementServer) {
	s.RegisterService(&_OrderManagement_serviceDesc, srv)
}

func _OrderManagement_UpdateOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrderManagementServer).UpdateOrders(&orderManagementUpdateOrdersServer{stream})
}

type OrderManagement_UpdateOrdersServer interface {
	SendAndClose(*wrappers.StringValue) error
	Recv() (*Order, error)
	grpc.ServerStream
}

type orderManagementUpdateOrdersServer struct {
	grpc.ServerStream
}

func (x *orderManagementUpdateOrdersServer) SendAndClose(m *wrappers.StringValue) error {
	return x.ServerStream.SendMsg(m)
}

func (x *orderManagementUpdateOrdersServer) Recv() (*Order, error) {
	m := new(Order)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _OrderManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ecommerce.OrderManagement",
	HandlerType: (*OrderManagementServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "updateOrders",
			Handler:       _OrderManagement_UpdateOrders_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "order_management.proto",
}
