// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order_management.proto

package ecommerce

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Items                []string `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Destination          string   `protobuf:"bytes,5,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_6653354279552460, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Order) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Order) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func init() {
	proto.RegisterType((*Order)(nil), "ecommerce.Order")
}

func init() {
	proto.RegisterFile("order_management.proto", fileDescriptor_6653354279552460)
}

var fileDescriptor_6653354279552460 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xcd, 0x4a, 0x03, 0x31,
	0x10, 0x80, 0xd9, 0xd4, 0x15, 0x37, 0x82, 0x4a, 0x10, 0x09, 0x45, 0x24, 0x78, 0xda, 0x53, 0x0a,
	0x7a, 0xf3, 0x1d, 0x8a, 0xb0, 0x82, 0x57, 0x49, 0x93, 0x31, 0x0c, 0x34, 0x3f, 0xcc, 0xa6, 0xf8,
	0x08, 0xbe, 0xb6, 0x34, 0xb1, 0x4b, 0x8f, 0x33, 0xf9, 0xbe, 0x30, 0x1f, 0x7f, 0x48, 0xe4, 0x80,
	0xbe, 0x82, 0x89, 0xc6, 0x43, 0x80, 0x58, 0x74, 0xa6, 0x54, 0x92, 0x18, 0xc0, 0xa6, 0x10, 0x80,
	0x2c, 0xac, 0x9f, 0x7c, 0x4a, 0x7e, 0x0f, 0x9b, 0xfa, 0xb0, 0x3b, 0x7c, 0x6f, 0x7e, 0xc8, 0xe4,
	0x0c, 0x34, 0x37, 0xf4, 0xf9, 0xb7, 0xe3, 0xfd, 0xfb, 0xf1, 0x17, 0x71, 0xc3, 0x19, 0x3a, 0xd9,
	0xa9, 0x6e, 0x1c, 0x26, 0x86, 0x4e, 0xdc, 0xf3, 0x1e, 0x0b, 0x84, 0x59, 0x32, 0xb5, 0x1a, 0x87,
	0xa9, 0x0d, 0x42, 0xf1, 0x6b, 0x07, 0xb3, 0x25, 0xcc, 0x05, 0x53, 0x94, 0xab, 0x8a, 0x9f, 0xaf,
	0x8e, 0x5e, 0x26, 0xb4, 0x20, 0x2f, 0x54, 0x37, 0xb2, 0xa9, 0x0d, 0xff, 0x5e, 0xc1, 0x68, 0xaa,
	0xd7, 0x2f, 0xde, 0x69, 0xf5, 0xb2, 0xe5, 0xb7, 0xf5, 0x90, 0xed, 0x52, 0x23, 0xde, 0xf8, 0x95,
	0x87, 0xd2, 0xce, 0x7b, 0xd4, 0xad, 0x44, 0x9f, 0x4a, 0xf4, 0x47, 0x21, 0x8c, 0xfe, 0xd3, 0xec,
	0x0f, 0xb0, 0xbe, 0xd3, 0x4b, 0xb2, 0xae, 0xfc, 0xee, 0xb2, 0x72, 0xaf, 0x7f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x58, 0x16, 0x7f, 0x4c, 0x24, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrderManagementClient is the client API for OrderManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderManagementClient interface {
	GetOrder(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*Order, error)
}

type orderManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderManagementClient(cc grpc.ClientConnInterface) OrderManagementClient {
	return &orderManagementClient{cc}
}

func (c *orderManagementClient) GetOrder(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := c.cc.Invoke(ctx, "/ecommerce.OrderManagement/getOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderManagementServer is the server API for OrderManagement service.
type OrderManagementServer interface {
	GetOrder(context.Context, *wrappers.StringValue) (*Order, error)
}

// UnimplementedOrderManagementServer can be embedded to have forward compatible implementations.
type UnimplementedOrderManagementServer struct {
}

func (*UnimplementedOrderManagementServer) GetOrder(ctx context.Context, req *wrappers.StringValue) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}

func RegisterOrderManagementServer(s *grpc.Server, srv OrderManagementServer) {
	s.RegisterService(&_OrderManagement_serviceDesc, srv)
}

func _OrderManagement_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderManagementServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ecommerce.OrderManagement/GetOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderManagementServer).GetOrder(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ecommerce.OrderManagement",
	HandlerType: (*OrderManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getOrder",
			Handler:    _OrderManagement_GetOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order_management.proto",
}
